package me.reckter.Entity.Category;

/**
 * Created by Hannes on 2/23/14.
 *
 * @author Hannes Güdelhöfer
 */
public enum Category {
    MOVEMENT,
    GRAVITY,
    REGENERATES,
    BOUNCES,
    PLAYER,
    ENEMY,
    FIGHTER,
    MAX_MOVEMENT,
    DAMAGABLE,
    PROJECTILE,
    GRENADE,
	NORMAL_PROJECTILE_COLLISION,
	MERGING,
	FOLLOWING,
	STANDART_SCORE,
	PLATFORM,
	PASSABLE_PLATFORM,
	NON_PASSABLE_PLATFORM,
	DAMAGE_PLATFORM,
	NEEDS_COLLISION_CHECKING,
	NEEDS_COLLISION_CHECKING_AGAINST

}
